//! Game Analytics API
//!
//! Provides endpoints for game-specific analytics including:
//! - Player session quality scoring
//! - Match analytics
//! - Geographic latency visualization
//! - Network quality heatmaps

#![allow(dead_code)] // Types module - some types used only for API responses

use anyhow::anyhow;
use axum::{
    extract::{Path, Query, State},
    http::HeaderMap,
    routing::get,
    Json, Router,
};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::sync::Arc;

use crate::app_state::WatchState;
use crate::error::{AppError, Result};

pub fn create_game_analytics_router() -> Router<Arc<WatchState>> {
    Router::new()
        .route("/sessions", get(list_player_sessions))
        .route("/sessions/{session_id}", get(get_player_session))
        .route("/sessions/{session_id}/quality", get(get_session_quality))
        .route("/matches", get(list_matches))
        .route("/matches/{match_id}", get(get_match))
        .route("/matches/{match_id}/players", get(get_match_players))
        .route("/latency/geo", get(get_geographic_latency))
        .route("/latency/heatmap", get(get_latency_heatmap))
        .route("/metrics/summary", get(get_game_metrics_summary))
}

// ============================================================================
// Request/Response Types
// ============================================================================

#[derive(Debug, Deserialize)]
pub struct SessionListQuery {
    #[serde(default)]
    pub player_id: Option<String>,
    #[serde(default)]
    pub platform: Option<String>,
    #[serde(default)]
    pub min_quality_score: Option<f64>,
    #[serde(default)]
    pub end_reason: Option<String>,
    #[serde(default = "default_limit")]
    pub limit: i32,
    #[serde(default)]
    pub offset: i32,
}

impl SessionListQuery {
    /// Validate and sanitize query parameters
    pub fn validated_limit(&self) -> i32 {
        self.limit.clamp(1, MAX_QUERY_LIMIT)
    }

    pub fn validated_offset(&self) -> i32 {
        self.offset.max(0)
    }

    /// Validate min_quality_score is a normal finite number
    pub fn validated_min_quality_score(&self) -> Option<f64> {
        self.min_quality_score
            .filter(|v| v.is_finite() && *v >= 0.0 && *v <= 100.0)
    }
}

#[derive(Debug, Deserialize)]
pub struct MatchListQuery {
    #[serde(default)]
    pub mode: Option<String>,
    #[serde(default)]
    pub map: Option<String>,
    #[serde(default)]
    pub server_region: Option<String>,
    #[serde(default)]
    pub outcome: Option<String>,
    #[serde(default = "default_limit")]
    pub limit: i32,
    #[serde(default)]
    pub offset: i32,
}

impl MatchListQuery {
    pub fn validated_limit(&self) -> i32 {
        self.limit.clamp(1, MAX_QUERY_LIMIT)
    }

    pub fn validated_offset(&self) -> i32 {
        self.offset.max(0)
    }
}

#[derive(Debug, Deserialize)]
pub struct MatchPlayersQuery {
    #[serde(default = "default_limit")]
    pub limit: i32,
    #[serde(default)]
    pub offset: i32,
}

impl MatchPlayersQuery {
    /// Maximum allowed players per request (reasonable limit for match context)
    const MAX_PLAYERS_LIMIT: i32 = 200;

    pub fn validated_limit(&self) -> i32 {
        self.limit.clamp(1, Self::MAX_PLAYERS_LIMIT)
    }

    pub fn validated_offset(&self) -> i32 {
        self.offset.max(0)
    }
}

// ============================================================================
// Path Parameter Validation
// ============================================================================

/// Validate that a session_id is a valid format.
///
/// Session IDs should be UUIDs (generated by the SDK as Guid.NewGuid().ToString()).
/// This validates the format to prevent malformed or malicious input.
fn validate_session_id(session_id: &str) -> Result<&str> {
    // Session IDs should be valid UUIDs
    uuid::Uuid::parse_str(session_id).map_err(|_| {
        AppError::Validation(format!(
            "Invalid session_id format: '{}'. Expected a valid UUID.",
            if session_id.len() > 50 {
                &session_id[..50]
            } else {
                session_id
            }
        ))
    })?;
    Ok(session_id)
}

/// Validate that a match_id is a valid format.
///
/// Match IDs should be UUIDs or alphanumeric identifiers.
/// This validates the format to prevent malformed or malicious input.
fn validate_match_id(match_id: &str) -> Result<&str> {
    // Try UUID format first (most common)
    if uuid::Uuid::parse_str(match_id).is_ok() {
        return Ok(match_id);
    }

    // Allow alphanumeric IDs with hyphens/underscores (max 64 chars)
    if match_id.len() <= 64
        && match_id
            .chars()
            .all(|c| c.is_alphanumeric() || c == '-' || c == '_')
    {
        return Ok(match_id);
    }

    Err(AppError::Validation(format!(
        "Invalid match_id format: '{}'. Expected a UUID or alphanumeric identifier.",
        if match_id.len() > 50 {
            &match_id[..50]
        } else {
            match_id
        }
    )))
}

#[derive(Debug, Deserialize)]
pub struct GeoLatencyQuery {
    #[serde(default)]
    pub server_region: Option<String>,
    #[serde(default)]
    pub time_range: Option<String>, // "1h", "24h", "7d"
}

fn default_limit() -> i32 {
    50
}

/// Maximum allowed limit for list queries to prevent resource exhaustion
const MAX_QUERY_LIMIT: i32 = 1000;

/// Allowed time range values for queries
const ALLOWED_TIME_RANGES: &[&str] = &["1h", "6h", "24h", "7d", "30d"];

fn validate_time_range(time_range: &str) -> &str {
    if ALLOWED_TIME_RANGES.contains(&time_range) {
        time_range
    } else {
        "24h" // Default to 24h if invalid
    }
}

#[derive(Debug, Serialize)]
pub struct PlayerSession {
    pub session_id: String,
    pub player_id: Option<String>,
    pub platform: String,
    pub device_model: String,
    pub gpu_model: String,
    pub game_version: String,
    pub start_time: DateTime<Utc>,
    pub end_time: Option<DateTime<Utc>>,
    pub duration_seconds: f64,
    pub end_reason: String,
    pub avg_fps: f64,
    pub min_fps: f64,
    pub p95_frame_time_seconds: f64,
    pub avg_rtt_seconds: f64,
    pub avg_jitter_seconds: f64,
    pub packet_loss_ratio: f64,
    pub peak_memory_bytes: u64,
    pub matches_played: u16,
    pub matches_completed: u16,
    pub quality_score: f64,
    pub country_code: String,
    pub region: String,
}

#[derive(Debug, Serialize)]
pub struct SessionQuality {
    pub session_id: String,
    pub overall_score: f64,
    pub fps_score: f64,
    pub latency_score: f64,
    pub stability_score: f64,
    pub network_score: f64,
    pub factors: Vec<QualityFactor>,
}

#[derive(Debug, Serialize)]
pub struct QualityFactor {
    pub name: String,
    pub weight: f64,
    pub score: f64,
    pub value: f64,
    pub threshold_good: f64,
    pub threshold_poor: f64,
}

#[derive(Debug, Serialize)]
pub struct GameMatch {
    pub match_id: String,
    pub match_mode: String,
    pub match_type: String,
    pub match_map: String,
    pub server_id: String,
    pub server_region: String,
    pub start_time: DateTime<Utc>,
    pub end_time: Option<DateTime<Utc>>,
    pub duration_seconds: f64,
    pub player_count: u16,
    pub max_player_count: u16,
    pub outcome: String,
    pub winning_team: String,
    pub avg_server_tick_rate: f64,
    pub avg_player_rtt_seconds: f64,
    pub max_player_rtt_seconds: f64,
    pub packet_loss_ratio: f64,
    pub error_count: u32,
    pub crash_count: u32,
}

#[derive(Debug, Serialize)]
pub struct MatchPlayer {
    pub session_id: String,
    pub player_id: Option<String>,
    pub team: String,
    pub join_time: DateTime<Utc>,
    pub leave_time: Option<DateTime<Utc>>,
    pub duration_seconds: f64,
    pub leave_reason: String,
    pub avg_fps: f64,
    pub avg_rtt_seconds: f64,
    pub packet_loss_ratio: f64,
}

#[derive(Debug, Serialize)]
pub struct GeoLatencyData {
    pub countries: Vec<CountryLatency>,
    pub regions: Vec<RegionLatency>,
}

#[derive(Debug, Serialize)]
pub struct CountryLatency {
    pub country_code: String,
    pub country_name: String,
    pub player_count: u64,
    pub avg_rtt_ms: f64,
    pub p95_rtt_ms: f64,
    pub avg_packet_loss: f64,
}

#[derive(Debug, Serialize)]
pub struct RegionLatency {
    pub region: String,
    pub server_region: String,
    pub player_count: u64,
    pub avg_rtt_ms: f64,
    pub min_rtt_ms: f64,
    pub max_rtt_ms: f64,
}

#[derive(Debug, Serialize)]
pub struct LatencyHeatmap {
    pub cells: Vec<HeatmapCell>,
    pub min_latency_ms: f64,
    pub max_latency_ms: f64,
}

#[derive(Debug, Serialize)]
pub struct HeatmapCell {
    pub client_region: String,
    pub server_region: String,
    pub avg_rtt_ms: f64,
    pub player_count: u64,
}

#[derive(Debug, Serialize)]
pub struct GameMetricsSummary {
    pub time_range: String,
    pub total_sessions: u64,
    pub total_matches: u64,
    pub unique_players: u64,
    pub avg_session_duration_seconds: f64,
    pub avg_match_duration_seconds: f64,
    pub avg_quality_score: f64,
    pub crash_rate: f64,
    pub abandonment_rate: f64,
    pub avg_fps: f64,
    pub avg_rtt_ms: f64,
    pub avg_packet_loss: f64,
    pub top_platforms: Vec<PlatformStats>,
    pub top_regions: Vec<RegionStats>,
}

#[derive(Debug, Serialize)]
pub struct PlatformStats {
    pub platform: String,
    pub session_count: u64,
    pub avg_fps: f64,
    pub crash_rate: f64,
}

#[derive(Debug, Serialize)]
pub struct RegionStats {
    pub region: String,
    pub player_count: u64,
    pub avg_rtt_ms: f64,
}

// ============================================================================
// ClickHouse Row Types
// ============================================================================

/// ClickHouse row type for player sessions query
#[derive(clickhouse::Row, Deserialize)]
struct PlayerSessionRow {
    session_id: String,
    player_id: Option<String>,
    platform: String,
    device_model: String,
    gpu_model: String,
    game_version: String,
    #[serde(with = "clickhouse::serde::chrono::datetime64::nanos")]
    start_time: DateTime<Utc>,
    #[serde(with = "clickhouse::serde::chrono::datetime64::nanos::option")]
    end_time: Option<DateTime<Utc>>,
    duration_seconds: f64,
    end_reason: String,
    avg_fps: f64,
    min_fps: f64,
    p95_frame_time_seconds: f64,
    avg_rtt_seconds: f64,
    avg_jitter_seconds: f64,
    packet_loss_ratio: f64,
    peak_memory_bytes: u64,
    matches_played: u16,
    matches_completed: u16,
    quality_score: f64,
    country_code: String,
    region: String,
}

/// ClickHouse row type for game matches query
#[derive(clickhouse::Row, Deserialize)]
struct GameMatchRow {
    match_id: String,
    match_mode: String,
    match_type: String,
    match_map: String,
    server_id: String,
    server_region: String,
    #[serde(with = "clickhouse::serde::chrono::datetime64::nanos")]
    start_time: DateTime<Utc>,
    #[serde(with = "clickhouse::serde::chrono::datetime64::nanos::option")]
    end_time: Option<DateTime<Utc>>,
    duration_seconds: f64,
    player_count: u16,
    max_player_count: u16,
    outcome: String,
    winning_team: String,
    avg_server_tick_rate: f64,
    avg_player_rtt_seconds: f64,
    max_player_rtt_seconds: f64,
    packet_loss_ratio: f64,
    error_count: u32,
    crash_count: u32,
}

/// ClickHouse row type for match players query
#[derive(clickhouse::Row, Deserialize)]
struct MatchPlayerRow {
    session_id: String,
    player_id: Option<String>,
    team: String,
    #[serde(with = "clickhouse::serde::chrono::datetime64::nanos")]
    join_time: DateTime<Utc>,
    #[serde(with = "clickhouse::serde::chrono::datetime64::nanos::option")]
    leave_time: Option<DateTime<Utc>>,
    duration_seconds: f64,
    leave_reason: String,
    avg_fps: f64,
    avg_rtt_seconds: f64,
    packet_loss_ratio: f64,
}

/// ClickHouse row type for country latency aggregation
#[derive(clickhouse::Row, Deserialize)]
struct CountryLatencyRow {
    country_code: String,
    player_count: u64,
    avg_rtt_ms: f64,
    p95_rtt_ms: f64,
    avg_packet_loss: f64,
}

/// ClickHouse row type for region latency aggregation
#[derive(clickhouse::Row, Deserialize)]
struct RegionLatencyRow {
    region: String,
    server_region: String,
    player_count: u64,
    avg_rtt_ms: f64,
    min_rtt_ms: f64,
    max_rtt_ms: f64,
}

/// ClickHouse row type for heatmap cells
#[derive(clickhouse::Row, Deserialize)]
struct HeatmapCellRow {
    client_region: String,
    server_region: String,
    avg_rtt_ms: f64,
    player_count: u64,
}

/// ClickHouse row type for metrics summary
#[derive(clickhouse::Row, Deserialize)]
struct MetricsSummaryRow {
    total_sessions: u64,
    total_matches: u64,
    unique_players: u64,
    avg_session_duration_seconds: f64,
    avg_match_duration_seconds: f64,
    avg_quality_score: f64,
    crash_rate: f64,
    abandonment_rate: f64,
    avg_fps: f64,
    avg_rtt_ms: f64,
    avg_packet_loss: f64,
}

/// ClickHouse row type for platform stats
#[derive(clickhouse::Row, Deserialize)]
struct PlatformStatsRow {
    platform: String,
    session_count: u64,
    avg_fps: f64,
    crash_rate: f64,
}

/// ClickHouse row type for region stats
#[derive(clickhouse::Row, Deserialize)]
struct RegionStatsRow {
    region: String,
    player_count: u64,
    avg_rtt_ms: f64,
}

// Country code to name mapping (subset for common countries)
fn get_country_name(code: &str) -> String {
    match code {
        "US" => "United States",
        "GB" => "United Kingdom",
        "CA" => "Canada",
        "DE" => "Germany",
        "FR" => "France",
        "JP" => "Japan",
        "KR" => "South Korea",
        "CN" => "China",
        "AU" => "Australia",
        "BR" => "Brazil",
        "IN" => "India",
        "RU" => "Russia",
        "MX" => "Mexico",
        "ES" => "Spain",
        "IT" => "Italy",
        "NL" => "Netherlands",
        "SE" => "Sweden",
        "PL" => "Poland",
        "TR" => "Turkey",
        "SG" => "Singapore",
        _ => code,
    }
    .to_string()
}

/// Convert time range string to ClickHouse interval
fn time_range_to_interval(time_range: &str) -> &'static str {
    match time_range {
        "1h" => "1 HOUR",
        "6h" => "6 HOUR",
        "24h" => "24 HOUR",
        "7d" => "7 DAY",
        "30d" => "30 DAY",
        _ => "24 HOUR",
    }
}

// ============================================================================
// API Handlers
// ============================================================================

async fn list_player_sessions(
    State(state): State<Arc<WatchState>>,
    headers: HeaderMap,
    Query(query): Query<SessionListQuery>,
) -> Result<Json<Vec<PlayerSession>>> {
    let project_id = crate::api::extract_project_id(&headers)?;

    // Use validated and sanitized parameters
    let limit = query.validated_limit();
    let offset = query.validated_offset();

    let mut conditions = vec!["project_id = ?".to_string()];

    if query.player_id.is_some() {
        conditions.push("player_id = ?".to_string());
    }

    if query.platform.is_some() {
        conditions.push("platform = ?".to_string());
    }

    if query.validated_min_quality_score().is_some() {
        conditions.push("quality_score >= ?".to_string());
    }

    if query.end_reason.is_some() {
        conditions.push("end_reason = ?".to_string());
    }

    let sql = format!(
        r#"
        SELECT
            session_id,
            player_id,
            platform,
            device_model,
            gpu_model,
            game_version,
            start_time,
            end_time,
            duration_seconds,
            end_reason,
            avg_fps,
            min_fps,
            p95_frame_time_seconds,
            avg_rtt_seconds,
            avg_jitter_seconds,
            packet_loss_ratio,
            peak_memory_bytes,
            matches_played,
            matches_completed,
            quality_score,
            country_code,
            region
        FROM reiver.game_player_sessions
        WHERE {}
        ORDER BY start_time DESC
        LIMIT ? OFFSET ?
        "#,
        conditions.join(" AND ")
    );

    // Build query with bound parameters
    let mut query_builder = state.clickhouse.as_ref().query(&sql);
    query_builder = query_builder.bind(project_id.to_string());

    if let Some(ref player_id) = query.player_id {
        query_builder = query_builder.bind(player_id.clone());
    }

    if let Some(ref platform) = query.platform {
        query_builder = query_builder.bind(platform.clone());
    }

    if let Some(min_score) = query.validated_min_quality_score() {
        query_builder = query_builder.bind(min_score);
    }

    if let Some(ref end_reason) = query.end_reason {
        query_builder = query_builder.bind(end_reason.clone());
    }

    query_builder = query_builder.bind(limit as u64).bind(offset as u64);

    // Execute query
    let rows: Vec<PlayerSessionRow> = query_builder
        .fetch_all()
        .await
        .map_err(|e| AppError::Internal(anyhow!("ClickHouse query failed: {}", e)))?;

    // Convert to API response type
    let sessions: Vec<PlayerSession> = rows
        .into_iter()
        .map(|row| PlayerSession {
            session_id: row.session_id,
            player_id: row.player_id,
            platform: row.platform,
            device_model: row.device_model,
            gpu_model: row.gpu_model,
            game_version: row.game_version,
            start_time: row.start_time,
            end_time: row.end_time,
            duration_seconds: row.duration_seconds,
            end_reason: row.end_reason,
            avg_fps: row.avg_fps,
            min_fps: row.min_fps,
            p95_frame_time_seconds: row.p95_frame_time_seconds,
            avg_rtt_seconds: row.avg_rtt_seconds,
            avg_jitter_seconds: row.avg_jitter_seconds,
            packet_loss_ratio: row.packet_loss_ratio,
            peak_memory_bytes: row.peak_memory_bytes,
            matches_played: row.matches_played,
            matches_completed: row.matches_completed,
            quality_score: row.quality_score,
            country_code: row.country_code,
            region: row.region,
        })
        .collect();

    Ok(Json(sessions))
}

async fn get_player_session(
    State(state): State<Arc<WatchState>>,
    headers: HeaderMap,
    Path(session_id): Path<String>,
) -> Result<Json<PlayerSession>> {
    // Validate session_id format to prevent malformed input
    let session_id = validate_session_id(&session_id)?;

    let project_id = crate::api::extract_project_id(&headers)?;

    let sql = r#"
        SELECT
            session_id,
            player_id,
            platform,
            device_model,
            gpu_model,
            game_version,
            start_time,
            end_time,
            duration_seconds,
            end_reason,
            avg_fps,
            min_fps,
            p95_frame_time_seconds,
            avg_rtt_seconds,
            avg_jitter_seconds,
            packet_loss_ratio,
            peak_memory_bytes,
            matches_played,
            matches_completed,
            quality_score,
            country_code,
            region
        FROM reiver.game_player_sessions
        WHERE project_id = ? AND session_id = ?
        LIMIT 1
    "#;

    let rows: Vec<PlayerSessionRow> = state
        .clickhouse
        .as_ref()
        .query(sql)
        .bind(project_id.to_string())
        .bind(&session_id)
        .fetch_all()
        .await
        .map_err(|e| AppError::Internal(anyhow!("ClickHouse query failed: {}", e)))?;

    let row = rows
        .into_iter()
        .next()
        .ok_or_else(|| AppError::NotFound(format!("Session {} not found", session_id)))?;

    Ok(Json(PlayerSession {
        session_id: row.session_id,
        player_id: row.player_id,
        platform: row.platform,
        device_model: row.device_model,
        gpu_model: row.gpu_model,
        game_version: row.game_version,
        start_time: row.start_time,
        end_time: row.end_time,
        duration_seconds: row.duration_seconds,
        end_reason: row.end_reason,
        avg_fps: row.avg_fps,
        min_fps: row.min_fps,
        p95_frame_time_seconds: row.p95_frame_time_seconds,
        avg_rtt_seconds: row.avg_rtt_seconds,
        avg_jitter_seconds: row.avg_jitter_seconds,
        packet_loss_ratio: row.packet_loss_ratio,
        peak_memory_bytes: row.peak_memory_bytes,
        matches_played: row.matches_played,
        matches_completed: row.matches_completed,
        quality_score: row.quality_score,
        country_code: row.country_code,
        region: row.region,
    }))
}

async fn get_session_quality(
    State(state): State<Arc<WatchState>>,
    headers: HeaderMap,
    Path(session_id): Path<String>,
) -> Result<Json<SessionQuality>> {
    // Validate session_id format to prevent malformed input
    let session_id = validate_session_id(&session_id)?;

    let project_id = crate::api::extract_project_id(&headers)?;

    // Calculate quality score with breakdown
    let quality = calculate_session_quality(&state, &project_id.to_string(), &session_id).await?;

    Ok(Json(quality))
}

#[allow(dead_code)]
fn _unused_to_silence_warnings() {
    // This function exists to acknowledge that some types are currently
    // only used for API response serialization
}

async fn list_matches(
    State(state): State<Arc<WatchState>>,
    headers: HeaderMap,
    Query(query): Query<MatchListQuery>,
) -> Result<Json<Vec<GameMatch>>> {
    let project_id = crate::api::extract_project_id(&headers)?;

    let limit = query.validated_limit();
    let offset = query.validated_offset();

    let mut conditions = vec!["project_id = ?".to_string()];

    if query.mode.is_some() {
        conditions.push("match_mode = ?".to_string());
    }
    if query.map.is_some() {
        conditions.push("match_map = ?".to_string());
    }
    if query.server_region.is_some() {
        conditions.push("server_region = ?".to_string());
    }
    if query.outcome.is_some() {
        conditions.push("outcome = ?".to_string());
    }

    let sql = format!(
        r#"
        SELECT
            match_id,
            match_mode,
            match_type,
            match_map,
            server_id,
            server_region,
            start_time,
            end_time,
            duration_seconds,
            player_count,
            max_player_count,
            outcome,
            winning_team,
            avg_server_tick_rate,
            avg_player_rtt_seconds,
            max_player_rtt_seconds,
            packet_loss_ratio,
            error_count,
            crash_count
        FROM reiver.game_matches
        WHERE {}
        ORDER BY start_time DESC
        LIMIT ? OFFSET ?
        "#,
        conditions.join(" AND ")
    );

    let mut query_builder = state.clickhouse.as_ref().query(&sql);
    query_builder = query_builder.bind(project_id.to_string());

    if let Some(ref mode) = query.mode {
        query_builder = query_builder.bind(mode.clone());
    }
    if let Some(ref map) = query.map {
        query_builder = query_builder.bind(map.clone());
    }
    if let Some(ref server_region) = query.server_region {
        query_builder = query_builder.bind(server_region.clone());
    }
    if let Some(ref outcome) = query.outcome {
        query_builder = query_builder.bind(outcome.clone());
    }

    query_builder = query_builder.bind(limit as u64).bind(offset as u64);

    let rows: Vec<GameMatchRow> = query_builder
        .fetch_all()
        .await
        .map_err(|e| AppError::Internal(anyhow!("ClickHouse query failed: {}", e)))?;

    let matches: Vec<GameMatch> = rows
        .into_iter()
        .map(|row| GameMatch {
            match_id: row.match_id,
            match_mode: row.match_mode,
            match_type: row.match_type,
            match_map: row.match_map,
            server_id: row.server_id,
            server_region: row.server_region,
            start_time: row.start_time,
            end_time: row.end_time,
            duration_seconds: row.duration_seconds,
            player_count: row.player_count,
            max_player_count: row.max_player_count,
            outcome: row.outcome,
            winning_team: row.winning_team,
            avg_server_tick_rate: row.avg_server_tick_rate,
            avg_player_rtt_seconds: row.avg_player_rtt_seconds,
            max_player_rtt_seconds: row.max_player_rtt_seconds,
            packet_loss_ratio: row.packet_loss_ratio,
            error_count: row.error_count,
            crash_count: row.crash_count,
        })
        .collect();

    Ok(Json(matches))
}

async fn get_match(
    State(state): State<Arc<WatchState>>,
    headers: HeaderMap,
    Path(match_id): Path<String>,
) -> Result<Json<GameMatch>> {
    // Validate match_id format to prevent malformed input
    let match_id = validate_match_id(&match_id)?;

    let project_id = crate::api::extract_project_id(&headers)?;

    let sql = r#"
        SELECT
            match_id,
            match_mode,
            match_type,
            match_map,
            server_id,
            server_region,
            start_time,
            end_time,
            duration_seconds,
            player_count,
            max_player_count,
            outcome,
            winning_team,
            avg_server_tick_rate,
            avg_player_rtt_seconds,
            max_player_rtt_seconds,
            packet_loss_ratio,
            error_count,
            crash_count
        FROM reiver.game_matches
        WHERE project_id = ? AND match_id = ?
        LIMIT 1
    "#;

    let rows: Vec<GameMatchRow> = state
        .clickhouse
        .as_ref()
        .query(sql)
        .bind(project_id.to_string())
        .bind(&match_id)
        .fetch_all()
        .await
        .map_err(|e| AppError::Internal(anyhow!("ClickHouse query failed: {}", e)))?;

    let row = rows
        .into_iter()
        .next()
        .ok_or_else(|| AppError::NotFound(format!("Match {} not found", match_id)))?;

    Ok(Json(GameMatch {
        match_id: row.match_id,
        match_mode: row.match_mode,
        match_type: row.match_type,
        match_map: row.match_map,
        server_id: row.server_id,
        server_region: row.server_region,
        start_time: row.start_time,
        end_time: row.end_time,
        duration_seconds: row.duration_seconds,
        player_count: row.player_count,
        max_player_count: row.max_player_count,
        outcome: row.outcome,
        winning_team: row.winning_team,
        avg_server_tick_rate: row.avg_server_tick_rate,
        avg_player_rtt_seconds: row.avg_player_rtt_seconds,
        max_player_rtt_seconds: row.max_player_rtt_seconds,
        packet_loss_ratio: row.packet_loss_ratio,
        error_count: row.error_count,
        crash_count: row.crash_count,
    }))
}

async fn get_match_players(
    State(state): State<Arc<WatchState>>,
    headers: HeaderMap,
    Path(match_id): Path<String>,
    Query(query): Query<MatchPlayersQuery>,
) -> Result<Json<Vec<MatchPlayer>>> {
    // Validate match_id format to prevent malformed input
    let match_id = validate_match_id(&match_id)?;

    let project_id = crate::api::extract_project_id(&headers)?;

    // Validate pagination parameters
    let limit = query.validated_limit();
    let offset = query.validated_offset();

    let sql = r#"
        SELECT
            session_id,
            player_id,
            team,
            join_time,
            leave_time,
            duration_seconds,
            leave_reason,
            avg_fps,
            avg_rtt_seconds,
            packet_loss_ratio
        FROM reiver.game_match_players
        WHERE project_id = ? AND match_id = ?
        ORDER BY join_time ASC
        LIMIT ? OFFSET ?
    "#;

    let rows: Vec<MatchPlayerRow> = state
        .clickhouse
        .as_ref()
        .query(sql)
        .bind(project_id.to_string())
        .bind(&match_id)
        .bind(limit as u64)
        .bind(offset as u64)
        .fetch_all()
        .await
        .map_err(|e| AppError::Internal(anyhow!("ClickHouse query failed: {}", e)))?;

    let players: Vec<MatchPlayer> = rows
        .into_iter()
        .map(|row| MatchPlayer {
            session_id: row.session_id,
            player_id: row.player_id,
            team: row.team,
            join_time: row.join_time,
            leave_time: row.leave_time,
            duration_seconds: row.duration_seconds,
            leave_reason: row.leave_reason,
            avg_fps: row.avg_fps,
            avg_rtt_seconds: row.avg_rtt_seconds,
            packet_loss_ratio: row.packet_loss_ratio,
        })
        .collect();

    Ok(Json(players))
}

async fn get_geographic_latency(
    State(state): State<Arc<WatchState>>,
    headers: HeaderMap,
    Query(query): Query<GeoLatencyQuery>,
) -> Result<Json<GeoLatencyData>> {
    let project_id = crate::api::extract_project_id(&headers)?;

    let time_range = validate_time_range(query.time_range.as_deref().unwrap_or("24h"));
    let interval = time_range_to_interval(time_range);

    // Query country-level latency stats
    let country_sql = format!(
        r#"
        SELECT
            country_code,
            count() as player_count,
            avg(avg_rtt_seconds) * 1000 as avg_rtt_ms,
            quantile(0.95)(avg_rtt_seconds) * 1000 as p95_rtt_ms,
            avg(packet_loss_ratio) as avg_packet_loss
        FROM reiver.game_player_sessions
        WHERE project_id = ? AND start_time >= now() - INTERVAL {}
        GROUP BY country_code
        ORDER BY player_count DESC
        LIMIT 50
        "#,
        interval
    );

    let country_rows: Vec<CountryLatencyRow> = state
        .clickhouse
        .as_ref()
        .query(&country_sql)
        .bind(project_id.to_string())
        .fetch_all()
        .await
        .map_err(|e| AppError::Internal(anyhow!("ClickHouse query failed: {}", e)))?;

    // Query region-level latency stats
    let mut region_sql = format!(
        r#"
        SELECT
            region,
            server_region,
            count() as player_count,
            avg(avg_rtt_seconds) * 1000 as avg_rtt_ms,
            min(avg_rtt_seconds) * 1000 as min_rtt_ms,
            max(avg_rtt_seconds) * 1000 as max_rtt_ms
        FROM reiver.game_player_sessions ps
        JOIN reiver.game_match_players mp ON ps.session_id = mp.session_id
        JOIN reiver.game_matches m ON mp.match_id = m.match_id
        WHERE ps.project_id = ? AND ps.start_time >= now() - INTERVAL {}
        "#,
        interval
    );

    if let Some(ref server_region) = query.server_region {
        region_sql.push_str(" AND m.server_region = ?");
        region_sql.push_str(" GROUP BY region, server_region ORDER BY player_count DESC LIMIT 50");

        let region_rows: Vec<RegionLatencyRow> = state
            .clickhouse
            .as_ref()
            .query(&region_sql)
            .bind(project_id.to_string())
            .bind(server_region.clone())
            .fetch_all()
            .await
            .map_err(|e| AppError::Internal(anyhow!("ClickHouse query failed: {}", e)))?;

        let regions: Vec<RegionLatency> = region_rows
            .into_iter()
            .map(|row| RegionLatency {
                region: row.region,
                server_region: row.server_region,
                player_count: row.player_count,
                avg_rtt_ms: row.avg_rtt_ms,
                min_rtt_ms: row.min_rtt_ms,
                max_rtt_ms: row.max_rtt_ms,
            })
            .collect();

        let countries: Vec<CountryLatency> = country_rows
            .into_iter()
            .map(|row| CountryLatency {
                country_name: get_country_name(&row.country_code),
                country_code: row.country_code,
                player_count: row.player_count,
                avg_rtt_ms: row.avg_rtt_ms,
                p95_rtt_ms: row.p95_rtt_ms,
                avg_packet_loss: row.avg_packet_loss,
            })
            .collect();

        return Ok(Json(GeoLatencyData { countries, regions }));
    }

    region_sql.push_str(" GROUP BY region, server_region ORDER BY player_count DESC LIMIT 50");

    let region_rows: Vec<RegionLatencyRow> = state
        .clickhouse
        .as_ref()
        .query(&region_sql)
        .bind(project_id.to_string())
        .fetch_all()
        .await
        .map_err(|e| AppError::Internal(anyhow!("ClickHouse query failed: {}", e)))?;

    let countries: Vec<CountryLatency> = country_rows
        .into_iter()
        .map(|row| CountryLatency {
            country_name: get_country_name(&row.country_code),
            country_code: row.country_code,
            player_count: row.player_count,
            avg_rtt_ms: row.avg_rtt_ms,
            p95_rtt_ms: row.p95_rtt_ms,
            avg_packet_loss: row.avg_packet_loss,
        })
        .collect();

    let regions: Vec<RegionLatency> = region_rows
        .into_iter()
        .map(|row| RegionLatency {
            region: row.region,
            server_region: row.server_region,
            player_count: row.player_count,
            avg_rtt_ms: row.avg_rtt_ms,
            min_rtt_ms: row.min_rtt_ms,
            max_rtt_ms: row.max_rtt_ms,
        })
        .collect();

    Ok(Json(GeoLatencyData { countries, regions }))
}

async fn get_latency_heatmap(
    State(state): State<Arc<WatchState>>,
    headers: HeaderMap,
    Query(query): Query<GeoLatencyQuery>,
) -> Result<Json<LatencyHeatmap>> {
    let project_id = crate::api::extract_project_id(&headers)?;
    let time_range = validate_time_range(query.time_range.as_deref().unwrap_or("24h"));
    let interval = time_range_to_interval(time_range);

    // Build client_region x server_region heatmap
    let sql = format!(
        r#"
        SELECT
            ps.region as client_region,
            m.server_region,
            avg(ps.avg_rtt_seconds) * 1000 as avg_rtt_ms,
            count() as player_count
        FROM reiver.game_player_sessions ps
        JOIN reiver.game_match_players mp ON ps.session_id = mp.session_id
        JOIN reiver.game_matches m ON mp.match_id = m.match_id
        WHERE ps.project_id = ? AND ps.start_time >= now() - INTERVAL {}
        GROUP BY ps.region, m.server_region
        HAVING player_count >= 10
        ORDER BY player_count DESC
        LIMIT 200
        "#,
        interval
    );

    let rows: Vec<HeatmapCellRow> = state
        .clickhouse
        .as_ref()
        .query(&sql)
        .bind(project_id.to_string())
        .fetch_all()
        .await
        .map_err(|e| AppError::Internal(anyhow!("ClickHouse query failed: {}", e)))?;

    let cells: Vec<HeatmapCell> = rows
        .iter()
        .map(|row| HeatmapCell {
            client_region: row.client_region.clone(),
            server_region: row.server_region.clone(),
            avg_rtt_ms: row.avg_rtt_ms,
            player_count: row.player_count,
        })
        .collect();

    let min_latency_ms = rows.iter().map(|r| r.avg_rtt_ms).fold(f64::MAX, f64::min);
    let max_latency_ms = rows.iter().map(|r| r.avg_rtt_ms).fold(0.0_f64, f64::max);

    Ok(Json(LatencyHeatmap {
        cells,
        min_latency_ms: if min_latency_ms == f64::MAX {
            0.0
        } else {
            min_latency_ms
        },
        max_latency_ms,
    }))
}

/// ClickHouse row type for match count query (used by get_game_metrics_summary)
#[derive(clickhouse::Row, Deserialize)]
struct MatchCountRow {
    total: u64,
    avg_duration: f64,
}

async fn get_game_metrics_summary(
    State(state): State<Arc<WatchState>>,
    headers: HeaderMap,
    Query(query): Query<GeoLatencyQuery>,
) -> Result<Json<GameMetricsSummary>> {
    let project_id = crate::api::extract_project_id(&headers)?;

    let time_range = validate_time_range(query.time_range.as_deref().unwrap_or("24h"));
    let interval = time_range_to_interval(time_range);
    let project_id_str = project_id.to_string();

    // Build all SQL queries upfront
    let summary_sql = format!(
        r#"
        SELECT
            count() as total_sessions,
            0 as total_matches,
            uniqExact(player_id) as unique_players,
            avg(duration_seconds) as avg_session_duration_seconds,
            0.0 as avg_match_duration_seconds,
            avg(quality_score) as avg_quality_score,
            countIf(end_reason = 'crash') / count() as crash_rate,
            countIf(end_reason = 'abandoned') / count() as abandonment_rate,
            avg(avg_fps) as avg_fps,
            avg(avg_rtt_seconds) * 1000 as avg_rtt_ms,
            avg(packet_loss_ratio) as avg_packet_loss
        FROM reiver.game_player_sessions
        WHERE project_id = ? AND start_time >= now() - INTERVAL {}
        "#,
        interval
    );

    let match_sql = format!(
        r#"
        SELECT count() as total, avg(duration_seconds) as avg_duration
        FROM reiver.game_matches
        WHERE project_id = ? AND start_time >= now() - INTERVAL {}
        "#,
        interval
    );

    let platform_sql = format!(
        r#"
        SELECT
            platform,
            count() as session_count,
            avg(avg_fps) as avg_fps,
            countIf(end_reason = 'crash') / count() as crash_rate
        FROM reiver.game_player_sessions
        WHERE project_id = ? AND start_time >= now() - INTERVAL {}
        GROUP BY platform
        ORDER BY session_count DESC
        LIMIT 10
        "#,
        interval
    );

    let region_sql = format!(
        r#"
        SELECT
            region,
            count() as player_count,
            avg(avg_rtt_seconds) * 1000 as avg_rtt_ms
        FROM reiver.game_player_sessions
        WHERE project_id = ? AND start_time >= now() - INTERVAL {}
        GROUP BY region
        ORDER BY player_count DESC
        LIMIT 10
        "#,
        interval
    );

    // Execute all 4 queries in parallel for better performance
    let (summary_result, match_result, platform_result, region_result) = tokio::join!(
        state
            .clickhouse
            .as_ref()
            .query(&summary_sql)
            .bind(project_id_str.clone())
            .fetch_all::<MetricsSummaryRow>(),
        state
            .clickhouse
            .as_ref()
            .query(&match_sql)
            .bind(project_id_str.clone())
            .fetch_all::<MatchCountRow>(),
        state
            .clickhouse
            .as_ref()
            .query(&platform_sql)
            .bind(project_id_str.clone())
            .fetch_all::<PlatformStatsRow>(),
        state
            .clickhouse
            .as_ref()
            .query(&region_sql)
            .bind(project_id_str)
            .fetch_all::<RegionStatsRow>()
    );

    // Process summary results
    let summary_row = summary_result
        .map_err(|e| AppError::Internal(anyhow!("ClickHouse query failed: {}", e)))?
        .into_iter()
        .next()
        .unwrap_or(MetricsSummaryRow {
            total_sessions: 0,
            total_matches: 0,
            unique_players: 0,
            avg_session_duration_seconds: 0.0,
            avg_match_duration_seconds: 0.0,
            avg_quality_score: 0.0,
            crash_rate: 0.0,
            abandonment_rate: 0.0,
            avg_fps: 0.0,
            avg_rtt_ms: 0.0,
            avg_packet_loss: 0.0,
        });

    // Process match count results
    let (total_matches, avg_match_duration) = match_result
        .unwrap_or_default()
        .into_iter()
        .next()
        .map(|r| (r.total, r.avg_duration))
        .unwrap_or((0, 0.0));

    // Process platform stats
    let top_platforms: Vec<PlatformStats> = platform_result
        .unwrap_or_default()
        .into_iter()
        .map(|row| PlatformStats {
            platform: row.platform,
            session_count: row.session_count,
            avg_fps: row.avg_fps,
            crash_rate: row.crash_rate,
        })
        .collect();

    // Process region stats
    let top_regions: Vec<RegionStats> = region_result
        .unwrap_or_default()
        .into_iter()
        .map(|row| RegionStats {
            region: row.region,
            player_count: row.player_count,
            avg_rtt_ms: row.avg_rtt_ms,
        })
        .collect();

    Ok(Json(GameMetricsSummary {
        time_range: time_range.to_string(),
        total_sessions: summary_row.total_sessions,
        total_matches,
        unique_players: summary_row.unique_players,
        avg_session_duration_seconds: summary_row.avg_session_duration_seconds,
        avg_match_duration_seconds: avg_match_duration,
        avg_quality_score: summary_row.avg_quality_score,
        crash_rate: summary_row.crash_rate,
        abandonment_rate: summary_row.abandonment_rate,
        avg_fps: summary_row.avg_fps,
        avg_rtt_ms: summary_row.avg_rtt_ms,
        avg_packet_loss: summary_row.avg_packet_loss,
        top_platforms,
        top_regions,
    }))
}

// ============================================================================
// Quality Score Calculation
// ============================================================================

/// ClickHouse row type for session quality metrics
#[derive(clickhouse::Row, Deserialize)]
struct SessionMetricsRow {
    avg_fps: f64,
    min_fps: f64,
    p95_frame_time_seconds: f64,
    avg_rtt_seconds: f64,
    avg_jitter_seconds: f64,
    packet_loss_ratio: f64,
}

/// Calculate a composite quality score for a player session.
///
/// The score is computed from multiple factors:
/// - FPS Score (30%): Based on average FPS and minimum FPS
/// - Latency Score (25%): Based on RTT and jitter
/// - Stability Score (25%): Based on frame time consistency and crashes
/// - Network Score (20%): Based on packet loss
///
/// Each factor is normalized to 0-100, then weighted to produce the final score.
async fn calculate_session_quality(
    state: &Arc<WatchState>,
    project_id: &str,
    session_id: &str,
) -> Result<SessionQuality> {
    // Fetch session metrics from ClickHouse
    let sql = r#"
        SELECT
            avg_fps,
            min_fps,
            p95_frame_time_seconds,
            avg_rtt_seconds,
            avg_jitter_seconds,
            packet_loss_ratio
        FROM reiver.game_player_sessions
        WHERE project_id = ? AND session_id = ?
        LIMIT 1
    "#;

    let rows: Vec<SessionMetricsRow> = state
        .clickhouse
        .as_ref()
        .query(sql)
        .bind(project_id)
        .bind(session_id)
        .fetch_all()
        .await
        .map_err(|e| AppError::Internal(anyhow!("ClickHouse query failed: {}", e)))?;

    let metrics = rows
        .into_iter()
        .next()
        .ok_or_else(|| AppError::NotFound(format!("Session {} not found", session_id)))?;

    let avg_fps = metrics.avg_fps;
    let min_fps = metrics.min_fps;
    let p95_frame_time = metrics.p95_frame_time_seconds;
    let avg_rtt = metrics.avg_rtt_seconds;
    let jitter = metrics.avg_jitter_seconds;
    let packet_loss = metrics.packet_loss_ratio;
    // Crash count is inferred from end_reason in a more complete implementation
    let crash_count: u32 = 0;

    // FPS Score (0-100)
    // 60+ FPS = 100, 30 FPS = 50, <15 FPS = 0
    let fps_score = calculate_fps_score(avg_fps, min_fps);

    // Latency Score (0-100)
    // <30ms = 100, 100ms = 50, >200ms = 0
    let latency_score = calculate_latency_score(avg_rtt, jitter);

    // Stability Score (0-100)
    // Based on frame time consistency and crash-free
    let stability_score = calculate_stability_score(p95_frame_time, avg_fps, crash_count);

    // Network Score (0-100)
    // 0% loss = 100, 2% loss = 50, >5% loss = 0
    let network_score = calculate_network_score(packet_loss);

    // Weighted average
    let overall_score =
        fps_score * 0.30 + latency_score * 0.25 + stability_score * 0.25 + network_score * 0.20;

    let factors = vec![
        QualityFactor {
            name: "FPS".to_string(),
            weight: 0.30,
            score: fps_score,
            value: avg_fps,
            threshold_good: 60.0,
            threshold_poor: 30.0,
        },
        QualityFactor {
            name: "Latency".to_string(),
            weight: 0.25,
            score: latency_score,
            value: avg_rtt * 1000.0, // Convert to ms for display
            threshold_good: 30.0,
            threshold_poor: 100.0,
        },
        QualityFactor {
            name: "Stability".to_string(),
            weight: 0.25,
            score: stability_score,
            value: p95_frame_time * 1000.0, // Convert to ms
            threshold_good: 16.67,          // 60fps target
            threshold_poor: 33.33,          // 30fps minimum
        },
        QualityFactor {
            name: "Network".to_string(),
            weight: 0.20,
            score: network_score,
            value: packet_loss * 100.0, // Convert to percentage
            threshold_good: 0.5,
            threshold_poor: 2.0,
        },
    ];

    Ok(SessionQuality {
        session_id: session_id.to_string(),
        overall_score,
        fps_score,
        latency_score,
        stability_score,
        network_score,
        factors,
    })
}

fn calculate_fps_score(avg_fps: f64, min_fps: f64) -> f64 {
    // Score based on average FPS (70%) and minimum FPS (30%)
    let avg_score = if avg_fps >= 60.0 {
        100.0
    } else if avg_fps >= 30.0 {
        50.0 + (avg_fps - 30.0) / 30.0 * 50.0
    } else if avg_fps >= 15.0 {
        (avg_fps - 15.0) / 15.0 * 50.0
    } else {
        0.0
    };

    let min_score = if min_fps >= 30.0 {
        100.0
    } else if min_fps >= 15.0 {
        50.0 + (min_fps - 15.0) / 15.0 * 50.0
    } else {
        (min_fps / 15.0) * 50.0
    };

    avg_score * 0.7 + min_score * 0.3
}

fn calculate_latency_score(avg_rtt_seconds: f64, jitter_seconds: f64) -> f64 {
    let rtt_ms = avg_rtt_seconds * 1000.0;
    let jitter_ms = jitter_seconds * 1000.0;

    // RTT score (80%)
    let rtt_score = if rtt_ms <= 30.0 {
        100.0
    } else if rtt_ms <= 100.0 {
        100.0 - (rtt_ms - 30.0) / 70.0 * 50.0
    } else if rtt_ms <= 200.0 {
        50.0 - (rtt_ms - 100.0) / 100.0 * 50.0
    } else {
        0.0
    };

    // Jitter score (20%)
    let jitter_score = if jitter_ms <= 5.0 {
        100.0
    } else if jitter_ms <= 20.0 {
        100.0 - (jitter_ms - 5.0) / 15.0 * 50.0
    } else if jitter_ms <= 50.0 {
        50.0 - (jitter_ms - 20.0) / 30.0 * 50.0
    } else {
        0.0
    };

    rtt_score * 0.8 + jitter_score * 0.2
}

fn calculate_stability_score(p95_frame_time_seconds: f64, avg_fps: f64, crash_count: u32) -> f64 {
    // Crash penalty
    if crash_count > 0 {
        return 0.0;
    }

    let p95_frame_time_ms = p95_frame_time_seconds * 1000.0;
    let target_frame_time_ms = 1000.0 / avg_fps.max(1.0);

    // How much variance from target frame time
    let variance_ratio = p95_frame_time_ms / target_frame_time_ms;

    if variance_ratio <= 1.2 {
        100.0
    } else if variance_ratio <= 1.5 {
        100.0 - (variance_ratio - 1.2) / 0.3 * 30.0
    } else if variance_ratio <= 2.0 {
        70.0 - (variance_ratio - 1.5) / 0.5 * 40.0
    } else {
        (30.0 / variance_ratio).max(0.0)
    }
}

fn calculate_network_score(packet_loss_ratio: f64) -> f64 {
    let loss_percent = packet_loss_ratio * 100.0;

    if loss_percent <= 0.5 {
        100.0
    } else if loss_percent <= 2.0 {
        100.0 - (loss_percent - 0.5) / 1.5 * 50.0
    } else if loss_percent <= 5.0 {
        50.0 - (loss_percent - 2.0) / 3.0 * 50.0
    } else {
        0.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_fps_score() {
        assert!((calculate_fps_score(60.0, 60.0) - 100.0).abs() < 0.01);
        // avg_fps=45: avg_score = 50 + (45-30)/30*50 = 75
        // min_fps=30: min_score = 100 (>= 30)
        // total = 0.7*75 + 0.3*100 = 82.5
        assert!((calculate_fps_score(45.0, 30.0) - 82.5).abs() < 1.0);
        assert!((calculate_fps_score(30.0, 15.0) - 50.0).abs() < 10.0);
    }

    #[test]
    fn test_latency_score() {
        assert!((calculate_latency_score(0.020, 0.003) - 100.0).abs() < 5.0);
        assert!((calculate_latency_score(0.065, 0.010) - 75.0).abs() < 10.0);
        assert!((calculate_latency_score(0.150, 0.030) - 25.0).abs() < 10.0);
    }

    #[test]
    fn test_network_score() {
        assert!((calculate_network_score(0.0) - 100.0).abs() < 0.01);
        // 0.01 = 1% packet loss
        // score = 100 - (1.0 - 0.5)/1.5 * 50 = 100 - 16.67 = 83.33
        assert!((calculate_network_score(0.01) - 83.33).abs() < 1.0);
        assert!((calculate_network_score(0.05) - 0.0).abs() < 0.01);
    }
}
