<template>
  <AppLayout :user="user" :current-project="project">
    <div class="max-w-[1200px] mx-auto px-8 py-6">
      <!-- Header -->
      <div class="mb-6">
        <div>
          <h1 class="text-2xl font-semibold text-gray-900">Query Editor</h1>
          <p class="text-sm text-gray-500 dark:text-gray-400 mt-1">
            Run federated queries across all your data sources
          </p>
        </div>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-4 gap-6">
        <!-- Sidebar: Available Sources -->
        <div class="lg:col-span-1">
          <BaseCard>
            <template #header>
              <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100">Data Sources</h2>
            </template>
            <div v-if="loadingSources" class="text-center py-4">
              <div class="spinner w-6 h-6 border-2 border-primary-600 border-t-transparent rounded-full mx-auto"></div>
            </div>
            <div v-else-if="sources.length === 0" class="text-center py-4 text-gray-500 text-sm">
              No sources configured
            </div>
            <div v-else class="space-y-2">
              <div
                v-for="source in sources"
                :key="source.id"
                class="p-2 rounded hover:bg-gray-100 dark:hover:bg-gray-800 cursor-pointer"
                @click="toggleSourceExpand(source.id)"
              >
                <div class="flex items-center justify-between">
                  <div class="flex items-center gap-2">
                    <svg
                      class="w-4 h-4 text-gray-400 transition-transform"
                      :class="{ 'rotate-90': expandedSources.includes(source.id) }"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                    </svg>
                    <span class="text-sm font-medium text-gray-900 dark:text-gray-100">{{ source.name }}</span>
                  </div>
                  <span
                    class="px-1.5 py-0.5 text-xs rounded"
                    :class="source.tier === 'cold' ? 'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300' : source.tier === 'warm' ? 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300' : 'bg-purple-100 text-purple-700 dark:bg-purple-900 dark:text-purple-300'"
                  >
                    {{ source.tier === 'cold' ? 'C' : source.tier === 'warm' ? 'W' : 'H' }}
                  </span>
                </div>
                <div v-if="expandedSources.includes(source.id) && sourceTables[source.id]" class="mt-2 ml-6 space-y-1">
                  <div
                    v-for="table in sourceTables[source.id]"
                    :key="table"
                    class="flex items-center gap-1 text-xs text-gray-600 dark:text-gray-400 hover:text-primary-600 cursor-pointer"
                    @click.stop="insertTableReference(source.name, table)"
                  >
                    <span class="flex-1 truncate">{{ table }}</span>
                    <router-link
                      :to="`/p/${$route.params.id}/warehouse/sources/${source.name}/tables/${table}`"
                      class="text-gray-400 hover:text-primary-500 flex-shrink-0"
                      @click.stop
                      title="View table details"
                    >
                      <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                      </svg>
                    </router-link>
                  </div>
                </div>
              </div>
            </div>
          </BaseCard>
        </div>

        <!-- Main: Query Editor -->
        <div class="lg:col-span-3 space-y-4">
          <!-- Natural Language Input -->
          <BaseCard>
            <template #header>
              <div class="flex items-center justify-between">
                <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100">Ask in Plain English</h2>
                <span v-if="nlResult" class="text-xs text-gray-500 dark:text-gray-400">
                  Generated by {{ nlResult.model_used }} in {{ nlResult.attempts }} attempt(s)
                </span>
              </div>
            </template>
            <div class="flex gap-2">
              <input
                v-model="nlQuestion"
                @keydown.enter="executeNLQuery"
                type="text"
                placeholder="Ask a question in plain English... (e.g., 'Show me the top 10 customers by revenue')"
                class="flex-1 px-4 py-2.5 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-600 rounded-lg text-sm text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent placeholder-gray-400"
              />
              <BaseButton variant="primary" size="sm" @click="executeNLQuery" :disabled="executingNL || !nlQuestion.trim()">
                <svg v-if="executingNL" class="animate-spin -ml-1 mr-1 h-4 w-4" fill="none" viewBox="0 0 24 24">
                  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path>
                </svg>
                {{ executingNL ? 'Generating...' : 'Ask' }}
              </BaseButton>
            </div>
            <div v-if="nlError" class="mt-2 text-sm text-red-600 dark:text-red-400">{{ nlError }}</div>
          </BaseCard>

          <!-- SQL Editor -->
          <BaseCard>
            <template #header>
              <div class="flex items-center justify-between">
                <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100">SQL Query</h2>
                <div class="flex items-center gap-2">
                  <select
                    v-model="outputFormat"
                    class="text-xs px-2 py-1 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded"
                  >
                    <option value="table">Table</option>
                    <option value="json">JSON</option>
                    <option value="csv">CSV</option>
                  </select>
                  <BaseButton variant="primary" size="sm" @click="runQuery" :disabled="aq.executing.value || !query.trim()">
                    <svg v-if="aq.executing.value" class="animate-spin -ml-1 mr-1 h-4 w-4" fill="none" viewBox="0 0 24 24">
                      <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                      <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path>
                    </svg>
                    {{ aq.executing.value ? 'Running...' : 'Run Query' }}
                  </BaseButton>
                </div>
              </div>
            </template>
            <div class="relative">
              <textarea
                ref="queryEditor"
                v-model="query"
                @keydown.ctrl.enter="runQuery"
                @keydown.meta.enter="runQuery"
                placeholder="SELECT * FROM source_name.table_name WHERE ..."
                class="w-full h-48 px-4 py-3 bg-gray-50 dark:bg-gray-900 border-0 rounded-lg font-mono text-sm text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-primary-500 resize-none"
              ></textarea>
              <div class="absolute bottom-2 right-2 text-xs text-gray-400">
                Ctrl+Enter to run
              </div>
            </div>
          </BaseCard>

          <!-- Query Results -->
          <BaseCard v-if="hasResults || aq.error.value">
            <template #header>
              <div class="flex items-center justify-between">
                <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100">
                  Results
                  <span v-if="hasResults" class="font-normal text-gray-500">
                    ({{ aq.processedResult.value.filteredCount }} of {{ aq.totalRows.value }} rows in {{ aq.executionTime.value }}ms)
                  </span>
                </h2>
                <div v-if="hasResults" class="flex items-center gap-2">
                  <button @click="aq.downloadCSV()" class="text-xs text-primary-600 hover:text-primary-700">
                    Download CSV
                  </button>
                  <button @click="aq.downloadJSON()" class="text-xs text-primary-600 hover:text-primary-700">
                    Download JSON
                  </button>
                  <button @click="aq.downloadArrowIPC()" class="text-xs text-primary-600 hover:text-primary-700">
                    Download Arrow
                  </button>
                </div>
              </div>
            </template>

            <!-- Error -->
            <div v-if="aq.error.value" class="p-4 bg-red-50 dark:bg-red-900/20 rounded-lg">
              <div class="flex items-start">
                <svg class="w-5 h-5 text-red-500 mt-0.5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <div>
                  <div class="font-medium text-red-700 dark:text-red-300">Query Error</div>
                  <div class="text-sm text-red-600 dark:text-red-400 mt-1 font-mono">{{ aq.error.value }}</div>
                </div>
              </div>
            </div>

            <!-- Active Filters -->
            <div v-if="Object.keys(aq.filters.value).length > 0" class="flex items-center gap-2 mb-3 flex-wrap">
              <span class="text-xs text-gray-500 dark:text-gray-400">Filters:</span>
              <span
                v-for="(filter, colName) in aq.filters.value"
                :key="colName"
                class="inline-flex items-center gap-1 px-2 py-0.5 bg-primary-100 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300 text-xs rounded-full"
              >
                {{ colName }} {{ filter.op }} {{ filter.value }}
                <button @click="aq.removeFilter(colName)" class="hover:text-primary-900 dark:hover:text-primary-100">
                  <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </span>
              <button @click="aq.clearFilters()" class="text-xs text-gray-500 hover:text-gray-700 dark:hover:text-gray-300">
                Clear all
              </button>
            </div>

            <!-- Table Results -->
            <div v-if="hasResults && outputFormat === 'table'" class="overflow-x-auto">
              <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                <thead class="bg-gray-50 dark:bg-gray-800">
                  <tr>
                    <th
                      v-for="col in aq.columns.value"
                      :key="col.name"
                      class="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700 select-none"
                      @click="aq.toggleSort(col.name)"
                    >
                      <div class="flex items-center gap-1">
                        {{ col.name }}
                        <span v-if="aq.sortColumn.value === col.name" class="text-primary-500">
                          {{ aq.sortDirection.value === 'asc' ? '\u2191' : '\u2193' }}
                        </span>
                      </div>
                    </th>
                  </tr>
                </thead>
                <tbody class="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-700">
                  <tr
                    v-for="(row, rowIdx) in aq.processedResult.value.rows"
                    :key="rowIdx"
                    class="hover:bg-gray-50 dark:hover:bg-gray-800"
                  >
                    <td
                      v-for="(col, colIdx) in aq.columns.value"
                      :key="col.name"
                      class="px-4 py-2 text-sm text-gray-900 dark:text-gray-100 whitespace-nowrap"
                    >
                      {{ formatCellValue(row[colIdx]) }}
                    </td>
                  </tr>
                </tbody>
              </table>
              <div v-if="aq.processedResult.value.rows.length === 0" class="text-center py-8 text-gray-500">
                No rows returned
              </div>

              <!-- Pagination Controls -->
              <div v-if="aq.processedResult.value.pageCount > 1" class="flex items-center justify-between px-4 py-3 border-t border-gray-200 dark:border-gray-700">
                <div class="text-xs text-gray-500 dark:text-gray-400">
                  Page {{ aq.currentPage.value + 1 }} of {{ aq.processedResult.value.pageCount }}
                  <span class="ml-2">
                    ({{ aq.processedResult.value.filteredCount }} rows)
                  </span>
                </div>
                <div class="flex items-center gap-2">
                  <select
                    :value="aq.pageSize.value"
                    @change="aq.setPageSize(Number($event.target.value))"
                    class="text-xs px-2 py-1 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded"
                  >
                    <option :value="50">50 / page</option>
                    <option :value="100">100 / page</option>
                    <option :value="250">250 / page</option>
                    <option :value="500">500 / page</option>
                    <option :value="1000">1000 / page</option>
                  </select>
                  <button
                    @click="aq.prevPage()"
                    :disabled="aq.currentPage.value === 0"
                    class="px-2 py-1 text-xs bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded disabled:opacity-50"
                  >
                    Prev
                  </button>
                  <button
                    @click="aq.nextPage()"
                    :disabled="aq.currentPage.value >= aq.processedResult.value.pageCount - 1"
                    class="px-2 py-1 text-xs bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded disabled:opacity-50"
                  >
                    Next
                  </button>
                </div>
              </div>

              <!-- Column Stats -->
              <div v-if="hasResults && showStats" class="px-4 py-3 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50">
                <div class="text-xs text-gray-500 dark:text-gray-400 mb-2 font-medium">Column Statistics (numeric columns)</div>
                <div class="grid grid-cols-2 md:grid-cols-4 gap-3">
                  <div v-for="(stats, colName) in computedStats" :key="colName" class="text-xs">
                    <div class="font-medium text-gray-700 dark:text-gray-300">{{ colName }}</div>
                    <div class="text-gray-500 dark:text-gray-400 space-y-0.5">
                      <div>Sum: {{ formatNumber(stats.sum) }}</div>
                      <div>Avg: {{ formatNumber(stats.avg) }}</div>
                      <div>Min: {{ formatNumber(stats.min) }} / Max: {{ formatNumber(stats.max) }}</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- JSON Results -->
            <div v-else-if="hasResults && outputFormat === 'json'" class="overflow-x-auto">
              <pre class="text-xs text-gray-800 dark:text-gray-200 font-mono p-4 bg-gray-50 dark:bg-gray-900 rounded overflow-auto max-h-96">{{ computedJSON }}</pre>
            </div>

            <!-- CSV Results -->
            <div v-else-if="hasResults && outputFormat === 'csv'" class="overflow-x-auto">
              <pre class="text-xs text-gray-800 dark:text-gray-200 font-mono p-4 bg-gray-50 dark:bg-gray-900 rounded overflow-auto max-h-96">{{ computedCSV }}</pre>
            </div>

            <!-- Toggle Stats -->
            <div v-if="hasResults && outputFormat === 'table'" class="px-4 py-2 border-t border-gray-200 dark:border-gray-700">
              <button
                @click="showStats = !showStats"
                class="text-xs text-primary-600 hover:text-primary-700"
              >
                {{ showStats ? 'Hide' : 'Show' }} column statistics
              </button>
            </div>
          </BaseCard>

          <!-- Query History -->
          <BaseCard v-if="queryHistory.length > 0">
            <template #header>
              <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100">Recent Queries</h2>
            </template>
            <div class="space-y-2">
              <div
                v-for="(item, idx) in queryHistory.slice(0, 5)"
                :key="idx"
                class="p-2 bg-gray-50 dark:bg-gray-800 rounded cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700"
                @click="query = item.query"
              >
                <div class="flex items-center justify-between">
                  <code class="text-xs text-gray-700 dark:text-gray-300 truncate flex-1">{{ item.query }}</code>
                  <span class="text-xs text-gray-400 ml-2">{{ item.time }}</span>
                </div>
              </div>
            </div>
          </BaseCard>
        </div>
      </div>
    </div>
  </AppLayout>
</template>

<script setup>
import { ref, reactive, computed, onMounted, watch } from 'vue';
import { useRoute } from 'vue-router';
import axios from 'axios';
import AppLayout from '@/Layouts/AppLayout.vue';
import BaseCard from '@/components/BaseCard.vue';
import BaseButton from '@/components/BaseButton.vue';
import { useAuth } from '@/composables/useAuth';
import { useArrowQuery } from '@/composables/useArrowQuery';

const route = useRoute();
const { user } = useAuth();
const aq = useArrowQuery();

const projectId = computed(() => route.params.id);
const project = computed(() => ({ id: projectId.value }));

const query = ref('');
const queryEditor = ref(null);
const outputFormat = ref('table');
const loadingSources = ref(false);
const sources = ref([]);
const expandedSources = ref([]);
const sourceTables = reactive({});
const queryHistory = ref([]);
const nlQuestion = ref('');
const executingNL = ref(false);
const nlError = ref(null);
const nlResult = ref(null);
const showStats = ref(false);

const hasResults = computed(() => aq.arrowTable.value !== null);

const computedStats = computed(() => {
  if (!hasResults.value || !showStats.value) return {};
  return aq.columnStats();
});

const computedJSON = computed(() => {
  if (!hasResults.value) return '[]';
  return aq.exportJSON();
});

const computedCSV = computed(() => {
  if (!hasResults.value) return '';
  return aq.exportCSV();
});

const toggleSourceExpand = async (sourceId) => {
  const idx = expandedSources.value.indexOf(sourceId);
  if (idx === -1) {
    expandedSources.value.push(sourceId);
    if (!sourceTables[sourceId]) {
      try {
        const response = await axios.get(`/api/projects/${projectId.value}/warehouse/sources/${sourceId}/tables`);
        sourceTables[sourceId] = response.data.tables || [];
      } catch (e) {
        console.error('Failed to load tables:', e);
      }
    }
  } else {
    expandedSources.value.splice(idx, 1);
  }
};

const insertTableReference = (sourceName, tableName) => {
  const tableRef = `${sourceName}.${tableName}`;
  if (queryEditor.value) {
    const start = queryEditor.value.selectionStart;
    query.value = query.value.slice(0, start) + tableRef + query.value.slice(queryEditor.value.selectionEnd);
  } else {
    query.value += tableRef;
  }
};

const runQuery = async () => {
  if (!query.value.trim() || aq.executing.value) return;
  showStats.value = false;

  await aq.executeQueryCached(projectId.value, query.value);

  if (!aq.error.value) {
    queryHistory.value.unshift({
      query: query.value,
      time: new Date().toLocaleTimeString()
    });
  }
};

const executeNLQuery = async () => {
  if (!nlQuestion.value.trim() || executingNL.value) return;

  executingNL.value = true;
  nlError.value = null;
  nlResult.value = null;
  showStats.value = false;

  try {
    const response = await axios.post(`/api/projects/${projectId.value}/warehouse/query/natural-language`, {
      question: nlQuestion.value,
    });

    nlResult.value = response.data;
    query.value = response.data.sql;

    await aq.executeQueryCached(projectId.value, response.data.sql);

    if (!aq.error.value) {
      queryHistory.value.unshift({
        query: response.data.sql,
        time: new Date().toLocaleTimeString(),
      });
    }
  } catch (e) {
    nlError.value = e.response?.data?.message || e.response?.data?.error || e.message;
  } finally {
    executingNL.value = false;
  }
};

const formatCellValue = (value) => {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
};

const formatNumber = (value) => {
  if (value === null || value === undefined) return '-';
  if (Number.isInteger(value)) return value.toLocaleString();
  return Number(value).toLocaleString(undefined, { maximumFractionDigits: 2 });
};

async function loadSourcesSidebar() {
  loadingSources.value = true;
  try {
    const response = await axios.get(`/api/projects/${projectId.value}/warehouse/sources`);
    sources.value = response.data;
  } catch (e) {
    console.error('Failed to load sources:', e);
  } finally {
    loadingSources.value = false;
  }
}

onMounted(loadSourcesSidebar);
watch(projectId, loadSourcesSidebar);
</script>

<style scoped>
.spinner {
  animation: spin 1s linear infinite;
}

@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}
</style>
