//! Catalog query engine for the pgwire server.
//!
//! Provides a DataFusion-based engine that handles `pg_catalog` and
//! `information_schema` queries from BI tools. Each project gets its own
//! cached `SessionContext` populated with schema-only MemTables derived
//! from `warehouse_catalog`.
//!
//! ## Architecture
//!
//! 1. Load `warehouse_catalog` entries for the project from Postgres
//! 2. Convert each table's `schema` JSONB (TypedColumn[]) to Arrow Schema
//! 3. Register as schema-only MemTables grouped by `source_name`
//! 4. Enable `information_schema` (auto-generated by DataFusion)
//! 5. Install `pg_catalog` via `datafusion-pg-catalog`
//! 6. Execute catalog SQL through DataFusion and return pgwire Responses

use std::collections::HashMap;
use std::sync::Arc;
use std::time::{Duration, Instant};

use arrow::datatypes::{Field, Schema};
use arrow::record_batch::RecordBatch;
use datafusion::catalog::memory::MemorySchemaProvider;
use datafusion::catalog::{MemTable, SchemaProvider};
use datafusion::prelude::{SessionConfig, SessionContext};
use datafusion_pg_catalog::pg_catalog::context::EmptyContextProvider;
use datafusion_pg_catalog::setup_pg_catalog;
use parking_lot::Mutex;
use pgwire::api::results::{FieldFormat, FieldInfo, Response};
use pgwire::error::{ErrorInfo, PgWireError, PgWireResult};
use sqlx::PgPool;
use uuid::Uuid;

use super::types::{arrow_type_to_pg, record_batches_to_response};
use crate::warehouse::types::TypedColumn;

/// Catalog name used in DataFusion (the top-level catalog).
const CATALOG_NAME: &str = "reiver";

/// Default schema name for tables that don't have an explicit source.
const DEFAULT_SCHEMA: &str = "public";

/// TTL for cached SessionContexts (seconds).
const CACHE_TTL_SECS: u64 = 60;

/// Maximum number of cached project contexts.
const CACHE_MAX_ENTRIES: usize = 256;

// ============================================================================
// Cache entry
// ============================================================================

struct CachedContext {
    ctx: Arc<SessionContext>,
    created_at: Instant,
}

impl CachedContext {
    fn is_expired(&self) -> bool {
        self.created_at.elapsed() > Duration::from_secs(CACHE_TTL_SECS)
    }
}

// ============================================================================
// CatalogQueryEngine
// ============================================================================

/// Engine for executing catalog (pg_catalog / information_schema) queries
/// using DataFusion as the local SQL engine.
pub struct CatalogQueryEngine {
    db: Arc<PgPool>,
    /// Simple HashMap cache protected by a Mutex. We don't need high concurrency
    /// on catalog queries, and the critical section is tiny (HashMap lookup).
    cache: Mutex<HashMap<Uuid, CachedContext>>,
}

impl CatalogQueryEngine {
    pub fn new(db: Arc<PgPool>) -> Self {
        Self {
            db,
            cache: Mutex::new(HashMap::new()),
        }
    }

    /// Execute a catalog query for the given project.
    ///
    /// Gets or creates a DataFusion SessionContext for the project,
    /// executes the SQL, and converts the result to pgwire format.
    pub async fn execute(
        &self,
        project_id: Uuid,
        sql: &str,
    ) -> PgWireResult<Vec<Response>> {
        let ctx = self.get_or_create_context(project_id).await?;

        let df = ctx.sql(sql).await.map_err(|e| {
            PgWireError::UserError(Box::new(ErrorInfo::new(
                "ERROR".to_owned(),
                "42000".to_owned(),
                format!("Catalog query error: {}", e),
            )))
        })?;

        let batches: Vec<RecordBatch> = df.collect().await.map_err(|e| {
            PgWireError::UserError(Box::new(ErrorInfo::new(
                "ERROR".to_owned(),
                "42000".to_owned(),
                format!("Catalog query execution error: {}", e),
            )))
        })?;

        record_batches_to_response(batches)
    }

    /// Describe the schema of a catalog query without executing it.
    ///
    /// Parses and plans the SQL to extract the output schema, then maps
    /// Arrow types to pgwire `FieldInfo`.
    pub async fn describe_schema(
        &self,
        project_id: Uuid,
        sql: &str,
    ) -> PgWireResult<Vec<FieldInfo>> {
        let ctx = self.get_or_create_context(project_id).await?;

        let df = ctx.sql(sql).await.map_err(|e| {
            PgWireError::UserError(Box::new(ErrorInfo::new(
                "ERROR".to_owned(),
                "42000".to_owned(),
                format!("Catalog query error: {}", e),
            )))
        })?;

        let schema = df.schema();
        let fields: Vec<FieldInfo> = schema
            .fields()
            .iter()
            .map(|f| {
                let pg_type = arrow_type_to_pg(f.data_type());
                FieldInfo::new(
                    f.name().clone(),
                    None,
                    None,
                    pg_type,
                    FieldFormat::Text,
                )
            })
            .collect();

        Ok(fields)
    }

    /// Get a cached context or create a new one.
    async fn get_or_create_context(
        &self,
        project_id: Uuid,
    ) -> PgWireResult<Arc<SessionContext>> {
        // Check cache first
        {
            let cache = self.cache.lock();
            if let Some(entry) = cache.get(&project_id) {
                if !entry.is_expired() {
                    return Ok(entry.ctx.clone());
                }
            }
        }

        // Cache miss or expired -- build a new context
        let ctx = Arc::new(self.build_context(project_id).await?);

        // Store in cache (evict old entries if over limit)
        {
            let mut cache = self.cache.lock();
            // Simple eviction: remove expired entries
            cache.retain(|_, v| !v.is_expired());
            // If still over limit, clear all (simple strategy)
            if cache.len() >= CACHE_MAX_ENTRIES {
                cache.clear();
            }
            cache.insert(
                project_id,
                CachedContext {
                    ctx: ctx.clone(),
                    created_at: Instant::now(),
                },
            );
        }

        Ok(ctx)
    }

    /// Build a fresh DataFusion SessionContext for a project.
    async fn build_context(&self, project_id: Uuid) -> PgWireResult<SessionContext> {
        // Load catalog entries
        let entries = self.load_catalog_entries(project_id).await?;

        // Create SessionContext with information_schema enabled
        let config = SessionConfig::new()
            .with_information_schema(true)
            .with_create_default_catalog_and_schema(true)
            .with_default_catalog_and_schema(CATALOG_NAME, DEFAULT_SCHEMA);

        let ctx = SessionContext::new_with_config(config);

        // Group tables by source_name
        let mut grouped: HashMap<String, Vec<CatalogEntry>> = HashMap::new();
        for entry in entries {
            grouped
                .entry(entry.source_name.clone())
                .or_default()
                .push(entry);
        }

        // Get the default catalog
        let catalog = ctx.catalog(CATALOG_NAME).ok_or_else(|| {
            PgWireError::UserError(Box::new(ErrorInfo::new(
                "ERROR".to_owned(),
                "XX000".to_owned(),
                "Failed to get default catalog".to_owned(),
            )))
        })?;

        // Register each source as a schema with its tables
        for (source_name, tables) in &grouped {
            let schema_provider = Arc::new(MemorySchemaProvider::new());

            for table in tables {
                let arrow_schema = build_arrow_schema(&table.columns);
                let mem_table = MemTable::try_new(Arc::new(arrow_schema), vec![vec![]])
                    .map_err(|e| {
                        PgWireError::UserError(Box::new(ErrorInfo::new(
                            "ERROR".to_owned(),
                            "XX000".to_owned(),
                            format!(
                                "Failed to create MemTable for {}.{}: {}",
                                source_name, table.table_name, e
                            ),
                        )))
                    })?;

                schema_provider
                    .register_table(table.table_name.clone(), Arc::new(mem_table))
                    .map_err(|e| {
                        PgWireError::UserError(Box::new(ErrorInfo::new(
                            "ERROR".to_owned(),
                            "XX000".to_owned(),
                            format!("Failed to register table: {}", e),
                        )))
                    })?;
            }

            catalog
                .register_schema(source_name, schema_provider)
                .map_err(|e| {
                    PgWireError::UserError(Box::new(ErrorInfo::new(
                        "ERROR".to_owned(),
                        "XX000".to_owned(),
                        format!("Failed to register schema {}: {}", source_name, e),
                    )))
                })?;
        }

        // Install pg_catalog (60+ tables, UDFs like format_type, pg_get_expr)
        setup_pg_catalog(&ctx, CATALOG_NAME, EmptyContextProvider)
            .map_err(|e| {
                PgWireError::UserError(Box::new(ErrorInfo::new(
                    "ERROR".to_owned(),
                    "XX000".to_owned(),
                    format!("Failed to setup pg_catalog: {}", e),
                )))
            })?;

        Ok(ctx)
    }

    /// Load catalog entries for a project from the warehouse_catalog table.
    async fn load_catalog_entries(
        &self,
        project_id: Uuid,
    ) -> PgWireResult<Vec<CatalogEntry>> {
        let rows: Vec<(String, String, serde_json::Value, Option<String>)> = sqlx::query_as(
            r#"
            SELECT
                source_name,
                table_name,
                schema,
                description
            FROM warehouse_catalog
            WHERE project_id = $1
            "#,
        )
        .bind(project_id)
        .fetch_all(&*self.db)
        .await
        .map_err(|e| {
            PgWireError::UserError(Box::new(ErrorInfo::new(
                "ERROR".to_owned(),
                "XX000".to_owned(),
                format!("Failed to load catalog entries: {}", e),
            )))
        })?;

        let mut entries = Vec::with_capacity(rows.len());
        for (source_name, table_name, schema_json, description) in rows {
            // Deserialize TypedColumn[] from the JSONB schema field
            let columns: Vec<TypedColumn> =
                serde_json::from_value(schema_json).unwrap_or_default();

            entries.push(CatalogEntry {
                source_name,
                table_name,
                columns,
                _description: description,
            });
        }

        Ok(entries)
    }
}

// ============================================================================
// Helper types
// ============================================================================

struct CatalogEntry {
    source_name: String,
    table_name: String,
    columns: Vec<TypedColumn>,
    _description: Option<String>,
}

/// Convert a list of `TypedColumn` into an Arrow `Schema`.
///
/// Uses each column's stored Arrow DataType (via `arrow_data_type_or_string()`)
/// and nullable flag to build the schema.
fn build_arrow_schema(columns: &[TypedColumn]) -> Schema {
    let fields: Vec<Field> = columns
        .iter()
        .map(|col| {
            let dt = col.arrow_data_type_or_string();
            Field::new(&col.name, dt, col.nullable)
        })
        .collect();
    Schema::new(fields)
}

// ============================================================================
// Query classification helpers
// ============================================================================

/// Check if a SQL query targets only catalog schemas (pg_catalog,
/// information_schema) and should be routed to DataFusion.
///
/// This uses sqlparser to extract table references from the query.
/// Returns `true` if all referenced tables are in catalog schemas.
pub fn is_catalog_query(sql: &str) -> bool {
    use sqlparser::dialect::PostgreSqlDialect;
    use sqlparser::parser::Parser;

    let dialect = PostgreSqlDialect {};
    let statements = match Parser::parse_sql(&dialect, sql) {
        Ok(stmts) => stmts,
        Err(_) => return false,
    };

    is_catalog_query_ast(&statements, sql)
}

/// Same as `is_catalog_query` but takes pre-parsed AST to avoid re-parsing.
pub fn is_catalog_query_ast(statements: &[sqlparser::ast::Statement], sql: &str) -> bool {
    if statements.is_empty() {
        return false;
    }

    let tables = extract_table_refs(statements);

    if tables.is_empty() {
        return is_system_function_query(sql);
    }

    tables.iter().all(|t| {
        let schema = t.schema.as_deref().unwrap_or("");
        schema.eq_ignore_ascii_case("pg_catalog")
            || schema.eq_ignore_ascii_case("information_schema")
    })
}

/// A table reference with optional schema qualifier.
struct TableRef {
    schema: Option<String>,
    name: String,
}

/// Extract table references from parsed SQL statements, excluding CTE aliases.
///
/// CTE aliases (e.g. `WITH foo AS (...)`) are collected so that references
/// to them in the outer query are not treated as unqualified data tables.
fn extract_table_refs(statements: &[sqlparser::ast::Statement]) -> Vec<TableRef> {
    let mut refs = Vec::new();
    let mut cte_names: Vec<String> = Vec::new();
    for stmt in statements {
        extract_from_statement(stmt, &mut refs, &mut cte_names);
    }
    // Remove refs that are just CTE aliases (no schema, name matches a CTE)
    refs.retain(|r| {
        if r.schema.is_some() {
            return true;
        }
        !cte_names.iter().any(|c| c.eq_ignore_ascii_case(&r.name))
    });
    refs
}

fn extract_from_statement(
    stmt: &sqlparser::ast::Statement,
    refs: &mut Vec<TableRef>,
    cte_names: &mut Vec<String>,
) {
    use sqlparser::ast::Statement;
    match stmt {
        Statement::Query(query) => extract_from_query(query, refs, cte_names),
        _ => {}
    }
}

fn extract_from_query(
    query: &sqlparser::ast::Query,
    refs: &mut Vec<TableRef>,
    cte_names: &mut Vec<String>,
) {
    if let Some(with) = &query.with {
        for cte in &with.cte_tables {
            cte_names.push(cte.alias.name.value.clone());
            extract_from_query(&cte.query, refs, cte_names);
        }
    }
    extract_from_set_expr(&query.body, refs);
}

fn extract_from_set_expr(set_expr: &sqlparser::ast::SetExpr, refs: &mut Vec<TableRef>) {
    use sqlparser::ast::SetExpr;
    match set_expr {
        SetExpr::Select(select) => {
            for table_with_joins in &select.from {
                extract_from_table_factor(&table_with_joins.relation, refs);
                for join in &table_with_joins.joins {
                    extract_from_table_factor(&join.relation, refs);
                }
            }
        }
        SetExpr::Query(query) => {
            let mut cte_names = Vec::new();
            extract_from_query(query, refs, &mut cte_names);
        }
        SetExpr::SetOperation { left, right, .. } => {
            extract_from_set_expr(left, refs);
            extract_from_set_expr(right, refs);
        }
        _ => {}
    }
}

fn extract_from_table_factor(factor: &sqlparser::ast::TableFactor, refs: &mut Vec<TableRef>) {
    use sqlparser::ast::TableFactor;
    match factor {
        TableFactor::Table { name, .. } => {
            let parts: Vec<&str> = name.0.iter().map(|i| i.value.as_str()).collect();
            let (schema, table) = match parts.len() {
                1 => (None, parts[0].to_owned()),
                2 => (Some(parts[0].to_owned()), parts[1].to_owned()),
                3 => (Some(parts[1].to_owned()), parts[2].to_owned()), // catalog.schema.table
                _ => return,
            };
            refs.push(TableRef {
                schema,
                name: table,
            });
        }
        TableFactor::Derived { subquery, .. } => {
            let mut cte_names = Vec::new();
            extract_from_query(subquery, refs, &mut cte_names);
        }
        TableFactor::NestedJoin { table_with_joins, .. } => {
            extract_from_table_factor(&table_with_joins.relation, refs);
            for join in &table_with_joins.joins {
                extract_from_table_factor(&join.relation, refs);
            }
        }
        _ => {}
    }
}

/// Check if a query with no table references is a system function call
/// that DataFusion can handle (e.g., SELECT current_database()).
fn is_system_function_query(sql: &str) -> bool {
    use sqlparser::ast::{Expr, SelectItem, SetExpr, Statement};
    use sqlparser::dialect::PostgreSqlDialect;
    use sqlparser::parser::Parser;

    const SYSTEM_FUNCTIONS: &[&str] = &[
        "CURRENT_DATABASE", "CURRENT_SCHEMA", "CURRENT_SCHEMAS",
        "CURRENT_USER", "SESSION_USER", "PG_BACKEND_PID", "VERSION",
        "PG_ENCODING_TO_CHAR", "FORMAT_TYPE", "PG_GET_USERBYID",
        "HAS_TABLE_PRIVILEGE", "HAS_SCHEMA_PRIVILEGE",
        "HAS_DATABASE_PRIVILEGE", "HAS_ANY_COLUMN_PRIVILEGE",
        "PG_TABLE_IS_VISIBLE", "QUOTE_IDENT", "PG_GET_EXPR",
        "PG_RELATION_SIZE", "PG_TOTAL_RELATION_SIZE",
    ];

    let dialect = PostgreSqlDialect {};
    let statements = match Parser::parse_sql(&dialect, sql.trim()) {
        Ok(s) => s,
        Err(_) => return false,
    };

    fn expr_has_system_function(expr: &Expr) -> bool {
        match expr {
            Expr::Function(f) => {
                let name = f.name.to_string().to_uppercase();
                SYSTEM_FUNCTIONS.iter().any(|s| name == *s)
            }
            Expr::Nested(inner) => expr_has_system_function(inner),
            Expr::BinaryOp { left, right, .. } => {
                expr_has_system_function(left) || expr_has_system_function(right)
            }
            Expr::Cast { expr, .. } => expr_has_system_function(expr),
            _ => false,
        }
    }

    for stmt in &statements {
        if let Statement::Query(query) = stmt {
            if let SetExpr::Select(select) = query.body.as_ref() {
                for item in &select.projection {
                    let has_sys = match item {
                        SelectItem::UnnamedExpr(e) | SelectItem::ExprWithAlias { expr: e, .. } => {
                            expr_has_system_function(e)
                        }
                        _ => false,
                    };
                    if has_sys {
                        return true;
                    }
                }
            }
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use arrow::datatypes::{DataType, Field, Schema};
    use datafusion::catalog::memory::MemorySchemaProvider;
    use datafusion::catalog::{MemTable, SchemaProvider};
    use datafusion::prelude::{SessionConfig, SessionContext};
    use std::sync::Arc;

    /// Verify that DataFusion's built-in information_schema auto-populates
    /// `information_schema.tables` and `information_schema.columns` from
    /// MemTables registered in the catalog.
    #[tokio::test]
    async fn test_information_schema_populated_from_memtables() {
        // Build a SessionContext with information_schema enabled
        let config = SessionConfig::new()
            .with_information_schema(true)
            .with_create_default_catalog_and_schema(true)
            .with_default_catalog_and_schema("pond", "default");
        let ctx = SessionContext::new_with_config(config);

        // Register a test schema with a MemTable
        let schema = Schema::new(vec![
            Field::new("id", DataType::Int64, false),
            Field::new("name", DataType::Utf8, true),
            Field::new("amount", DataType::Float64, true),
        ]);
        let mem_table = MemTable::try_new(Arc::new(schema), vec![vec![]]).unwrap();
        let schema_provider = Arc::new(MemorySchemaProvider::new());
        schema_provider
            .register_table("test_orders".to_owned(), Arc::new(mem_table))
            .unwrap();

        ctx.catalog("pond")
            .unwrap()
            .register_schema("my_source", schema_provider)
            .unwrap();

        // Query information_schema.tables -- should list our MemTable
        let df = ctx
            .sql("SELECT table_catalog, table_schema, table_name FROM information_schema.tables WHERE table_schema = 'my_source'")
            .await
            .unwrap();
        let batches = df.collect().await.unwrap();
        let row_count: usize = batches.iter().map(|b| b.num_rows()).sum();
        assert!(
            row_count >= 1,
            "Expected at least 1 table in information_schema.tables for 'my_source', got {}",
            row_count
        );

        // Query information_schema.columns -- should list our 3 columns
        let df = ctx
            .sql("SELECT column_name, data_type FROM information_schema.columns WHERE table_schema = 'my_source' AND table_name = 'test_orders' ORDER BY ordinal_position")
            .await
            .unwrap();
        let batches = df.collect().await.unwrap();
        let col_count: usize = batches.iter().map(|b| b.num_rows()).sum();
        assert_eq!(
            col_count, 3,
            "Expected 3 columns in information_schema.columns for test_orders, got {}",
            col_count
        );
    }

    #[test]
    fn test_is_catalog_query() {
        assert!(is_catalog_query("SELECT * FROM pg_catalog.pg_type"));
        assert!(is_catalog_query("SELECT * FROM information_schema.tables"));
        assert!(!is_catalog_query("SELECT * FROM orders"));
    }

    #[test]
    fn test_is_system_function_query() {
        assert!(is_catalog_query("SELECT current_database()"));
        assert!(is_catalog_query("SELECT VERSION()"));
        assert!(!is_catalog_query("SELECT 1"));
    }

    // ── is_catalog_query edge cases ──

    #[test]
    fn test_catalog_query_parse_error() {
        // Malformed SQL should return false, not panic
        assert!(!is_catalog_query("NOT VALID @#$"));
    }

    #[test]
    fn test_catalog_query_empty_string() {
        assert!(!is_catalog_query(""));
    }

    #[test]
    fn test_catalog_query_mixed_join() {
        // A JOIN between a catalog table and a data table → NOT a catalog query
        // because not ALL tables are in pg_catalog/information_schema
        assert!(!is_catalog_query(
            "SELECT * FROM pg_catalog.pg_type t JOIN orders o ON t.oid = o.type_id"
        ));
    }

    #[test]
    fn test_catalog_query_cte_with_catalog_table() {
        // CTE referencing pg_catalog should be detected as catalog query
        let sql = "WITH types AS (SELECT oid, typname FROM pg_catalog.pg_type) SELECT * FROM types";
        assert!(is_catalog_query(sql));
    }

    #[test]
    fn test_catalog_query_three_part_name() {
        // catalog.schema.table -- the schema part is pg_catalog
        assert!(is_catalog_query(
            "SELECT * FROM reiver.pg_catalog.pg_type"
        ));
    }

    #[test]
    fn test_catalog_query_subquery() {
        // Subquery with catalog table in FROM
        assert!(is_catalog_query(
            "SELECT * FROM (SELECT oid FROM pg_catalog.pg_type) AS sub"
        ));
    }

    #[test]
    fn test_catalog_query_select_literal() {
        // SELECT 1 with no tables and no system function → not a catalog query
        assert!(!is_catalog_query("SELECT 1"));
    }

    #[test]
    fn test_catalog_query_leading_whitespace() {
        // Leading whitespace should still parse correctly
        assert!(is_catalog_query("   SELECT version()"));
    }

    // ── is_system_function_query patterns ──

    #[test]
    fn test_system_function_all_patterns() {
        // Test all 19 system function patterns are recognized
        let patterns = vec![
            "SELECT current_database()",
            "SELECT current_schema()",
            "SELECT current_schemas(true)",
            "SELECT current_user",
            "SELECT session_user",
            "SELECT pg_backend_pid()",
            "SELECT version()",
            "SELECT pg_encoding_to_char(6)",
            "SELECT format_type(23, -1)",
            "SELECT pg_get_userbyid(10)",
            "SELECT has_table_privilege('users', 'SELECT')",
            "SELECT has_schema_privilege('public', 'USAGE')",
            "SELECT has_database_privilege('mydb', 'CONNECT')",
            "SELECT has_any_column_privilege('users', 'SELECT')",
            "SELECT pg_table_is_visible(16384)",
            "SELECT quote_ident('my_table')",
            "SELECT pg_get_expr(adbin, adrelid) FROM pg_catalog.pg_attrdef",
            "SELECT pg_relation_size('users')",
            "SELECT pg_total_relation_size('users')",
        ];

        for sql in &patterns {
            assert!(
                is_catalog_query(sql),
                "Expected is_catalog_query=true for: {}",
                sql
            );
        }
    }

    #[test]
    fn test_system_function_non_select() {
        // Non-SELECT statements should not match even if they contain system function names
        // (e.g. an UPDATE/INSERT mentioning version -- though these would normally be
        // rejected by read-only guard, catalog detection should still return false)
        assert!(!is_catalog_query("DO $$ BEGIN RAISE NOTICE 'version'; END $$"));
    }

    // ── Compound catalog queries ──

    #[test]
    fn test_catalog_query_multi_catalog_join() {
        // JOIN between two catalog schemas should still be a catalog query
        let sql = "SELECT t.oid, c.column_name \
                   FROM pg_catalog.pg_type t \
                   JOIN information_schema.columns c ON t.typname = c.data_type";
        assert!(
            is_catalog_query(sql),
            "JOIN between pg_catalog and information_schema should be a catalog query"
        );
    }

    #[test]
    fn test_catalog_query_union_catalog_and_data() {
        // UNION between catalog table and data table should NOT be a catalog query
        let sql = "SELECT oid AS id FROM pg_catalog.pg_type \
                   UNION SELECT id FROM orders";
        assert!(
            !is_catalog_query(sql),
            "UNION of catalog + data tables should not be a catalog query"
        );
    }

    // ── Additional routing edge cases ──

    #[test]
    fn test_catalog_query_unqualified_pg_type() {
        // pg_type without schema qualifier should NOT be detected as catalog
        assert!(
            !is_catalog_query("SELECT * FROM pg_type"),
            "Unqualified pg_type should not be treated as catalog query"
        );
    }

    #[test]
    fn test_catalog_query_multi_statement_mixed() {
        // Multiple statements: first is catalog, second is data -- should return false
        // because extract_table_refs processes all statements and orders has no schema
        assert!(
            !is_catalog_query("SELECT * FROM pg_catalog.pg_type; SELECT * FROM orders"),
            "Mixed multi-statement should not be a catalog query"
        );
    }

    #[test]
    fn test_catalog_query_subquery_plus_data_table() {
        // Catalog subquery joined with a data table -- should be false
        let sql = "SELECT * FROM (SELECT * FROM pg_catalog.pg_type) t, orders";
        assert!(
            !is_catalog_query(sql),
            "Catalog subquery + data table should not be a catalog query"
        );
    }
}
