apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: clickhouse
spec:
  replicas: 1
  shards: 1
  containerTemplate:
    resources:
      requests:
        cpu: 500m
        memory: 4Gi
      limits:
        cpu: "4"
        memory: 32Gi
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  keeperClusterRef:
    name: clickhouse-keeper
  settings:
    extraUsersConfig:
      profiles:
        default:
          optimize_skip_unused_shards: 1
    extraConfig:
      merge_tree:
        merge_with_ttl_timeout: 3600
        ttl_only_drop_parts: 1
